#!/bin/bash
if [ -z "$VIRTUAL_ENV" ]; then
  source venv.sh
fi

if [[ $1 == "bootstrap" ]]; then
  #sudo chown -R "$USER" /usr/local
  ansible-playbook -i hosts bootstrap.yml -vv
elif [[ $1 == "core" ]]; then
  ansible-playbook -i hosts "$1" -v --ask-become-pass --tags="core"
else
  ansible-playbook -i hosts "$1" -v --ask-become-pass --tags="$2"
fi
