#!/bin/bash
export ANSIBLE_NOCOWS=1

get_ssh_from_root() {
  # Decrypt ssh key used to fetch secrets
  mkdir -p ~/.ssh
  # Fetch files copied by live.sh
  sudo cp /root/main_id.{pub,gpg} ~/.ssh/
  sudo chown "$USER:$USER" ~/.ssh/main_id*
  gpg -d ~/.ssh/main_id.gpg > ~/.ssh/main_id
  chmod 0600 ~/.ssh/main_id
  chmod 0644 ~/.ssh/main_id.pub
  rm ~/.ssh/main_id.gpg
}

fetch_secret_repos() {
  echo "Unlocking gogs.gpg - 'library' password please"
  gpg -d vars/gogs.yml.gpg > vars/gogs.yml
  echo "Unlocking main_id ssh key - password please"
  keychain --timeout 30 --quiet --host agent ~/.ssh/main_id
  source ~/.keychain/agent-sh
  ansible-playbook -i hosts -l "$(hostname)" -e 'host_key_checking=False' secrets.yml -vvv
}

setup_dotfiles() {
  mkdir -p ~/repos && cd ~/repos
  git clone git@github.com:clux/dotfiles.git
  cd dotfiles
  make config
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  make vim
  git clone https://github.com/powerline/fonts.git powerline-fonts
  ./powerline-fonts/install.sh
  make ui
}

main() {
  set -e
  if [[ $1 == "bootstrap" ]]; then
    if [[ $EUID -ne 0 ]]; then
      echo "Must run bootstrap role as root"
      exit 1
    fi
    pacman -S --noconfirm ansible
    ansible-playbook -i hosts -l "$(hostname)" bootstrap.yml -vv
  elif [[ $1 == "secrets" ]]; then
    if [[ $EUID -eq 0 ]]; then
      echo "This role is not indended to be run as root"
      exit 1
    fi
    # interactive steps with passwords and key pasting here:
    set -x
    sudo chown -R "$USER:$USER" /usr/local # First sudo
    # If we haven't set up our ssh key from genprov, do so now
    [ -f ~/.ssh/main_id ] || get_ssh_from_root
    # If we haven't installed the last secret repo, fetch all repos
    [ -f ~/.ssh/work_id ] || fetch_secret_repos
    # Install repos we haven't yet installed
    [ -d ~/.gnupg/.git ] || ~/gpg/install.sh
    [ -f ~/.config/Mumble/Mumble.conf ] || ~/mumble/install.sh
    [ -d ~/.ssh/.git ] || ~/ssh/install.sh
    # Delete the rest
    rm -rf ~/ssh ~/gpg ~/mumble
    # Set up dotfiles
    [ -L ~/.functions ] || setup_dotfiles
  else
    # arg parse
    OPTIND=2 # getopts start
    while getopts ":fcvs" opt; do
      case $opt in
        f) FULL=1 ;;
        c) RECOMPILE=1 ;;
        v) VERBOSE="v" ;;
        s) SUDO=1 ;;
        \?) echo Invalid option -"$OPTARG"; exit 1 ;;
      esac
    done
    set -x
    # shellcheck disable=SC2046
    ansible-playbook -i hosts -l "$(hostname)" site.yml --tags="$1" "-vv${VERBOSE}" \
      $([ -n "$FULL" ] && echo "-e upgrade_tasks=1" || echo "") \
      $([ -n "$RECOMPILE" ] && echo "-e recompile_tasks=1" || echo "") \
      $([ -n "$SUDO" ] && echo "--become" || echo "")
    bats test
  fi
}

# If we were not sourced as a library, pass arguments onto main
if [ "$0" = "${BASH_SOURCE[0]}" ]; then
  main "$@"
else
  echo "${BASH_SOURCE[0]} sourced"
fi
