#!/bin/bash
if [ -z "$VIRTUAL_ENV" ]; then
  source venv.sh
fi

if [[ $1 == "bootstrap" ]]; then
  if [[ $EUID -ne 0 ]]; then
    echo "Must run bootstrap role as root"
    exit 1
  fi
  ansible-playbook -i hosts -l "$(hostname)" bootstrap.yml -vv
  chown -R "$USER:$USER" /usr/local
elif [[ $1 == "secrets" ]]; then
  if [[ $EUID -eq 0 ]]; then
    echo "This role is not indended to be run as root"
    exit 1
  fi
  gpg -d vars/gogs.yml.gpg > vars/gogs.yml
  ansible-playbook -i hosts -l "$(hostname)" secrets.yml -vv
else
  # shellcheck disable=SC2046
  ansible-playbook -i hosts -l "$(hostname)" site.yml --tags="$1" -vv \
    $(test -n "$DOTCLUX_FULL" && echo "-e upgrade_tasks=1" || echo "") \
    --ask-become-pass
fi
