#!/bin/sh

# set name and email
git config --global user.name "clux"
git config --global user.email "analsandblaster@gmail.com"

# git 2.0 push default
git config --global push.default simple

# pretty log from http://coderwall.com/p/euwpig?i=3&p=1&t=git
git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"

# pretty diff
git config --global alias.dif "diff --color"

# pretty diff stat
git config --global alias.stat = "diff --color --stat"

# hg st equivalent
git config --global alias.st "status -s"

# short commit alias
git config --global alias.ci "commit"
git config --global alias.cia "commit -am"

# rename last commit
git config --global alias.amend "commit --amend -m"

# empty commit to ping github hooks like travis
git config --global alias.ping "commit --allow-empty -m \"ping hooks\""

# undo last commit
git config --global alias.undo "reset --soft HEAD^"

# move --cached diffs back out of staging area (add file for specifics)
git config --global alias.unstage "git reset HEAD"

# tj style contributors count
git config --global alias.count "shortlog -sn"


# generate ssh keys
ssh-keygen -t rsa -C "analsandblaster@gmail.com"
xclip -sel clip < ~/.ssh/github_id_rsa.pub
echo "LOG IN TO DVCS AND PASTE RSA KEY (IN CLIPBOARD NOW)"
echo "VERIFY GITHUB WITH: ssh -T git@github.com"
