#!/usr/bin/env bash

# google public key + sources list
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
#echo "deb http://dl.google.com/linux/talkplugin/deb/ stable main" > /etc/apt/sources.list.d/google-talkplugin.list

apt-get update
apt-get upgrade

apps=(
  #cheese      # camera tester
  #clementine  # music player
  cmake     # c++ build tool
  #couchdb     # json database
  cppcheck  # c++ linter
  google-chrome-stable  # stable chrome from googles repo
  #google-talkplugin     # google talk plugin (still needed?)
  grc       # generic colouriser
  handbrake # encoding/transcoding utility
  lcov      # c++ coverage
  pidgin    # XMPP
  mumble    # MP voice com
  redshift  # monitor night brightener
  screen    # screen manager
  shellcheck # bash script linter
  steam     # games
  vlc       # video player
)

for i in ${apps[@]}
do
  echo $i
  apt-get install -y -qq $i
done
