#!/usr/bin/env bash
set -e
# this is an ssh safe install of node that works with pm2-deploy

abort() {  echo "$@" 1>&2 && exit 1; }

version=$(wget -qO- https://nodejs.org/download/release/index.tab | sed -n 2p | cut -f1)
test -n "$version" || abort missing nodejs.org/download/release/index.tab

echo installing $version
mkdir -p ~/local/node-$version
cd ~/local/node-$version
wget -qO- https://nodejs.org/download/release/$version/node-$version-linux-x64.tar.gz | tar xz --strip-components=1

# Prepend to PATH in .bashrc (BEFORE INTERACTIVE CUTOUT) to make it work in ssh commands
echo "export PATH=\$HOME/local/node-$version/bin:\$PATH" | cat - ~/.bashrc > ~/tmpbashrc
mv ~/tmpbashrc ~/.bashrc
echo "Edit .bashrc to disable old versions"

# using new node install (hence sh wrap) fetch latest headers for node-gyp
if which node-gyp-install; then
  sh node-gyp-install -v $version
else
  sh npm i node-gyp-install -g
  sh node-gyp-install -v $version
fi
