#!/bin/sh

# node install script
# usage ./node 0.8.12

echo 'export PATH=$HOME/local/bin:$PATH' >> ~/.bashrc
. ~/.bashrc
cd ~/Downloads
mkdir node-v$1
cd node-v$1
curl http://nodejs.org/dist/v$1/node-v$1.tar.gz | tar xz --strip-components=1
./configure --prefix=$HOME/local/node
make
make install


