#!/bin/sh

# all local installs
echo 'export PATH=$HOME/local/bin:$PATH' >> ~/.bashrc

# texlive (should probably do a non-admin install of this in the future)
echo 'export PATH=/usr/local/texlive/2012/bin/i386-linux:$PATH' >> ~/.bashrc

# npm tab completion
npm completion >> ~/.bashrc
