#!/usr/bin/env bash

# only set prefix if we didn't install from source
#npm config set prefix ~/npm
#npm config set loglevel info

globalModules=(
  ansimd      # markdown viewer terminal
  jshint      # static analysis
  jsonlint    # analysis of json files
  json        # curl jsonUrl | json key
  nd          # nd `moduleName` for README.md in stdout
  npm         # alwyas update this
  pkginit     # for quick making a npm module shell (though bugged atm)
  browserify  # npm style webapps
  testling    # for browser tests
  asciify     # CLI asciifier
  ytdl        # streaming youtube downloader
  bower       # web components currently here..
  # tests
  nodeunit
  tap
  coveralls
)
for i in ${globalModules[@]}
do
  echo $i
  npm install -g $i
done

pkginit add default pkg.json

cd && cd repos

# private bitbucket repos
privates=(
  deathmatch
  meshrtc
)
for i in ${privates[@]}
do
  echo $i
  git clone git@bitbucket.org:clux/$i.git
done

modules=(
  autonomy
  badgify
  blog
  cleverbot-irc
  combustion
  confortable
  curvefever-bot
  curvefever-stats
  decay
  dotclux
  duel
  dye
  ffa
  ffa-tb
  group
  groupstage
  groupstage-tb
  groupstage-tb-duel
  gu
  icebreaker
  interlude
  irc-stream
  linkr-app
  linkr-components
  logule
  masters
  npm-graph
  operators
  posts
  preservative
  sdp-transform
  splitter
  statesoftheworld
  subset
  symlink
  roundrobin
  tabexplode
  tf2configs
  tiebreaker
  topiary
  tournament
  tournament-components
  tourney
  trials
  tub
  vitae
  wolfram-alpha
  wolfram-irc
  wrappers
)

for i in ${modules[@]}
do
  echo $i
  git clone git@github.com:clux/$i.git
done

echo "Preparing to symlink"
npm install symlink
echo "Dry run results:"
$(npm bin)/symlinks . -d
echo "Doing it properly:"
$(npm bin)/symlink . -g nodeunit -g coveralls
rm -rf node_modules/
