#!/usr/bin/env bash

# install all stuff I either use or develop
# assumes node installed and usr/local/lib/node_modules chowned

npm install -g cdir browserify jshint jsontool nd tap

modules=(
  autonomy
  wrappers
  operators
  subset
  interlude
  typr
  topiary
  decay
  combustion
  confortable
  fsx
  tap-pessimist
  logule
  modul8
)

for i in ${modules[@]}
do
  echo $i
  git clone git@github.com:clux/$i.git
  cd $i && npm link tap && cd ..
done

# # misc dependency linking
cd interlude && npm link operators subset autonomy wrappers && cd ..
cd autonomy && npm link operators && cd ..
cd combustion && npm link fsx confortable autonomy operators && cd ..
cd tap-pessimist && npm link logule && cd ..
cd logule && npm link autonomy confortable subset && cd ..
cd modul8 && npm link autonomy logule topiary typr && cd ..

for i in ${modules[@]}
do
  echo $i
  cd $i && npm install && cd ..
done

# non-node modules, just clone
others=(
  tournament.hs
  setup
  vitae
)

for i in ${others[@]}
do
  echo $i
  git clone git@github.com:clux/$i.git
done
