#!/usr/bin/env bash

npm install -g cdir jshint jsontool nd tap pkginit browserify
pkginit add default pkg.json

cd && cd repos

# private bitbucket repos
privates=(
  deathmatch
  meshrtc
  sexify
)
for i in ${privates[@]}
do
  echo $i
  git clone git@bitbucket.org:clux/$i.git
done

modules=(
  blog
  posts
  fsx
  operators
  typr
  topiary
  wrappers
  decay
  subset
  symlink
  dye
  autonomy
  interlude
  confortable
  combustion
  logule
  tournament
  trials
  statesoftheworld
  tub
  splitter
  vitae
  .clux
)

for i in ${modules[@]}
do
  echo $i
  git clone git@github.com:clux/$i.git
done

