---
- name: provision secrets from gogs post bootstrap
  connection: local
  hosts: all
  vars_files:
  - vars/gogs.yml
  user: "{{ user }}"
  tasks:
  - name: provision an initial ssh config
    template:
      src: templates/ssh_config.j2
      dest: /home/{{ user }}/.ssh/config
      mode: 0755

  - name: Checkout secret modules
    git:
      repo: 'git@{{ gogs_name }}:{{ gogs_user }}/{{ item }}.git'
      dest: /home/{{ user }}/{{ item }}
      key_file: /home/{{ user }}/.ssh/{{ gogs_ssh_id }}
      accept_hostkey: true
      update: false # noqa: latest
    with_items:
    - ssh
    - gpg
