---
- connection: local
  hosts: all
  vars_files:
  - vars/gogs.yml
  user: "{{ user }}"
  tasks:
  - template: src=templates/ssh_config.j2 dest=/home/{{ user }}/.ssh/config

  - name: Checkout secret modules
    git:
      repo=git@{{ gogs_name }}:{{ gogs_user }}/{{ item }}.git
      dest=/home/{{ user }}/{{ item }}
      key_file=/home/{{ user }}/.ssh/{{ gogs_ssh_id }}
      accept_hostkey=yes
      update=no
    with_items:
    - ssh
    - gpg
