#!/bin/sh

# ensure rc exists
touch ~/.bashrc

# write in what's in our default
cat bashrc >> ~/.bashrc

# npm tab completion and linking of node executables
~/local/node/bin/npm completion >> ~/.bashrc

# make local bin for other apps
mkdir -p ~/local/bin
