---
- name: provision machine post-bootstrap
  connection: local
  hosts: all
  user: "{{ user }}"
  gather_facts: true
  roles:
  - { role: arch, when: ansible_os_family == "Archlinux" }
  - disks
  - lpms
  - docker
  - ssh
  #- xdg
