#!/usr/bin/env bash

echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
echo "deb http://dl.google.com/linux/talkplugin/deb/ stable main" > /etc/apt/sources.list.d/google-talkplugin.list
sudo add-apt-repository ppa:team-xbmc

sudo apt-get update
sudo apt-get upgrade

apps=(
  cheese
  clementine
  cowsay
  google-chrome-stable
  google-talkplugin
  guake
  pidgin
  mercurial
  vlc
  xbmc
)

for i in ${apps[@]}
do
  echo $i
  sudo apt-get install -y -qq $i
done
