#!/usr/bin/env bash

echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
echo "deb http://dl.google.com/linux/talkplugin/deb/ stable main" > /etc/apt/sources.list.d/google-talkplugin.list
sudo add-apt-repository ppa:team-xbmc
sudo add-apt-repository ppa:webupd8team/gnome3
sudo add-apt-repository ppa:ferramroberto/gnome3

sudo apt-get update
sudo apt-get upgrade

apps=(
  cheese
  clementine
  cowsay
  google-chrome-stable
  google-talkplugin
  gnome-shell
  gnome-tweak-tool
  gnome-shell-extensions
  gnome-shell-extensions-common
  gnome-shell-extensions-pidgin
  gnome-shell-extensions-mediaplayer
  gnome-shell-extensions-alternative-status-menu
  gnome-shell-extensions-windows-navigator
  guake
  pidgin
  mercurial
  vlc
  xbmc
)

for i in ${apps[@]}
do
  echo $i
  sudo apt-get install -y -qq $i
done


#keyboard change to colemak and add shortcut keys

# echo remember notices for certain programs like truecrypt

