#!/usr/bin/env bash

wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
apt-get update

apps=(
  #cheese      # camera tester
  #clementine  # music player
  cmake     # c++ build tool
  #couchdb     # json database
  cppcheck  # c++ linter
  curl      # wget alternative
  g++
  git
  google-chrome-stable
  grc       # generic colouriser
  guake
  handbrake # encoding/transcoding utility
  lcov      # c++ coverage
  pass      # password store
  pidgin    # XMPP
  mumble    # MP voice com
  nmap      # port scanner
  redshift  # monitor night brightener
  screen    # screen manager
  shellcheck # bash script linter
  steam     # games
  vlc       # video player
  xclip     # clipboard helper
  xsel      # clipboard helper
)

for i in ${apps[@]}
do
  echo $i
  apt-get install -y -qq $i
done
