#!/bin/sh

wget -qO- https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
apt-get update
apt-get install google-chrome-stable guake # get these early

# get everything else in one line
apt-get install -y -qq \
  cmake \
  cppcheck \
  curl \
  g++ \
  git \
  grc  \
  handbrake \
  lcov \
  pass \
  pidgin \
  mumble \
  nmap \
  redshift \
  shellcheck \
  vlc \
  xclip
