#!/bin/sh

wget -qO- https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
apt-get update
apt-get install -y -qq google-chrome-stable guake # get these early

# get everything else in one line
apt-get install -y -qq \
  ccze \
  cmake \
  cppcheck \
  curl \
  g++ \
  git \
  handbrake \
  htop \
  iftop \
  lcov \
  lolcat \
  pass \
  php5-cli \
  php5-curl \
  pidgin \
  python-keyring \
  sshfs \
  mumble \
  nmap \
  redshift \
  shellcheck \
  vlc \
  vim-gnome \
  xclip

# remove output of dpkg -l | grep zeitgeist
apt-get purge libzeitgeist-* zeitgeist
apt-get autoremove
