#!/usr/bin/env bash
set -x
# install local bashrc
echo "source $PWD/bashrc" >> ~/.bashrc

# install completion scripts at the bottom of bashrc..
[ -z "$TRAVIS" ] && pm2 completion install
npm completion >> ~/.bashrc
