#!/usr/bin/env sh
dir=$(cd "$(dirname "$1")"; echo "$(pwd -P)/$(basename "$1")")
echo "Removing temporary reference to this directory ($dir) in bashrc"
escdir=$(echo "$dir" | sed 's_/_\\/_g')
sed -i "$escdir/d" ~/.bashrc
