#!/usr/bin/env bash
mkdir -p ~/local/bin
cd ~/local

# bats
wget -qO- https://github.com/sstephenson/bats/archive/v0.4.0.tar.gz | tar xz
./bats*/install.sh

# fasd (z)
wget -qO- https://github.com/clvv/fasd/archive/1.0.1.tar.gz | tar xz
cd fasd-* && PREFIX=$HOME/local make install && cd -

# blackbox
wget -qO- https://github.com/StackExchange/blackbox/archive/stable.tar.gz | tar xz
cd blackbox-stable && make manual-install && cd -

# arc
# NB: These rely on PATH containing ~/local/bin and ~/local/arcanist/bin to work
git clone ${GH}phacility/libphutil.git
git clone ${GH}phacility/arcanist.git
