#!/usr/bin/env bash

cd && mkdir -p repos && cd repos

if [ -z "$TRAVIS" ]; then
  secrets=(
    dotcisco
    gpg-pass
    mumble-keys
    ssh
  )
  for repo in ${secrets[@]}
  do
    echo $repo
    git clone git@bitbucket.org:clux/$repo.git
  done
  mv dotcisco dotwork # old habbit
  ./ssh/install.sh
  ./gpg-pass/install.sh
  ./mumble-keys/install.sh
fi

# tournament related modules
cd && cd repos
mkdir tournament && cd tournament
trn=(
  duel
  duel-names
  ffa
  ffa-tb
  group
  groupstage
  groupstage-tb
  groupstage-tb-duel
  masters
  roundrobin
  tiebreaker
  tournament
  tournament-components
  tourney
)
for repo in ${trn[@]}
do
  git clone $giturl/$repo.git
done

misc=(
  autonomy
  #badgify
  bandage
  blog
  cleverbot-irc
  combustion
  confortable
  #curvefever-bot
  #curvefever-stats
  decay
  deus-login
  dotclux
  dye
  gu
  icebreaker
  interlude
  irc-stream
  linkr-app
  linkr-components
  #logule
  mddocs
  mumble-bot
  npm-graph
  operators
  posts
  preservative
  sdp-transform
  smell
  splitter
  subset
  sulfur
  #symlink
  #tabexplode
  tf2configs
  topiary
  trials
  tub
  unitednationsoftheworld
  vitae
  wolfram-alpha
  wolfram-irc
  wrappers
  #xmpp-stream
  zalgolize
)

cd && cd repos

for repo in ${misc[@]}
do
  echo $repo
  git clone ${gh}clux/$repo.git
done

cd
symlink repos repos/tournament --execute
