#!/usr/bin/env bash
set -ex

mkdir -p ~/repos && cd ~/repos

# general modules
modules=(
  bandage
  blog
  deus-login
  dye
  gu
  icebreaker
  irc-stream
  linkr-app
  linkr-components
  mddocs
  posts
  sdp-transform
  smell
  sulfur
  topiary
)
for i in "${modules[@]}"; do
  git clone "${GH}clux/$i"
done

# tournament related modules
cd ~/repos && mkdir -p tournament && cd tournament
tournament=(
  duel
  duel-names
  ffa
  ffa-tb
  group
  groupstage
  groupstage-tb
  groupstage-tb-duel
  masters
  roundrobin
  tiebreaker
  tournament
  tourney
)
for i in "${tournament[@]}"; do
  git clone "${GH}clux/$i"
done

# functional libraries
cd ~/repos && mkdir interlude && cd interlude
interlude=(
  autonomy
  interlude
  operators
  subset
  wrappers
)

for i in "${interlude[@]}"; do
  git clone "${GH}clux/$i"
done

cd
symlink repos repos/tournament repos/interlude --execute


# Don't check these out at the moment
# Keeping this comment here as a reminder why they are kept out of above lists
notcloneds=(
  badgify # globally installed
  cleverbot-irc # stable, deployed
  combustion # not in use atm, but good
  confortable # stable, in use everywhere
  curvefever-bot # unmaintained, broken
  curvefever-stats # unmaintained, broken
  decay # stable, working
  logule # stable, but overcomplicated and unmaintained (using sulphur+smell)
  mumble-bot # just for laughs
  npm-graph # not in use atm
  splitter # not in use atm
  tabexplode # not in use atm
  trials # stable, working
  typr # stable, not needed
  tub # globally installed
  unitednationsoftheworld # song
  wolfram-alpha # stable, working
  wolfram-irc # stable, deployed
  xmpp-stream # experimental, and no need for atm
  zalgolize # globally installed
)
