#!/usr/bin/env bash

# sublime 3
mkdir -p ~/.config/sublime-text-3/Packages/
ln -s $PWD/configs/ST3User/ ~/.config/sublime-text-3/Packages/User

# symlink misc configs
ln -s $PWD/configs/.eslintrc ~/
ln -s $PWD/configs/.jshintrc ~/
ln -s $PWD/configs/pep8 ~/.config/
ln -s $PWD/configs/redshift.conf ~/.config/
ln -s $PWD/configs/.gitconfig ~/

# autostart + gconf settings
cp -R configs/gconf/* ~/.gconf/
cp configs/autostart/* ~/.config/autostart

# TODO: maybe look at keyboard layouts + shortcut keys

# user picture
cp configs/iface ~/.iface
