#!/bin/sh

cp configs/.jshintrc ~/
cp configs/.eslintrc ~/
cp configs/gitconfig ~/.gitconfig
cp configs/pep8 ~/.config
cp configs/redshift.conf  ~/.config/

# sublime 3
rm -rf ~/.config/sublime-text-3/Cache/JavaScript/
cp -R sublime-text-3/ ~/.config/

# autostart + gconf settings
cp -R configs/gconf/* ~/.gconf/
cp configs/autostart/* ~/.config/autostart

# TODO: maybe look at keyboard layouts + shortcut keys

# user picture
cp iface ~/.iface
