#!/usr/bin/env bash

# llvm install script
# usage ./llvm 3.7.0

abort() {
  echo "$@" 1>&2
  exit 1
}

ver=$1

hash clang 2> /dev/null && clang --version | grep -q "$ver"
test $? -eq 0  && abort clang version $ver already installed

LLVM=http://llvm.org/releases/$ver/llvm-$ver.src.tar.xz
CLANG=http://llvm.org/releases/$ver/cfe-$ver.src.tar.xz
EXTRA=http://llvm.org/releases/$ver/clang-tools-extra-$ver.src.tar.xz
COMPILERRT=http://llvm.org/releases/$ver/compiler-rt-$ver.src.tar.xz

cd ~
mkdir -p local/llvm-v$ver && cd local/llvm-v$ver
echo "fetch $LLVM"
wget $LLVM
echo "fetch $CLANG"
wget $CLANG
echo "fetch $EXTRA"
wget $EXTRA
echo "fetch $COMPILERRT"
wget $COMPILERRT

mkdir src && cd src
tar xf ../llvm-$ver.src.tar.xz --strip-components=1
# clang goes in tools/clang
mkdir -p tools/clang && cd tools/clang
tar xf ../../../cfe-$ver.src.tar.xz --strip-components=1
# extra goes in tools/clang/tools/extra
mkdir -p tools/extra && cd tools/extra
tar xf ../../../../../clang-tools-extra-$ver.src.tar.xz --strip-components=1
# compiler-rt goes in projects/compiler-rt
cd ../../../../
mkdir -p projects/compiler-rt && cd projects/compiler-rt
tar xf ../../../compiler-rt-$ver.src.tar.xz --strip-components=1

# back to source
cd ../..

# don't pollute src dir with build stuff
mkdir build
cd build
../configure
make -j8
sudo make install

cd ..
echo "Remember to:"
echo "export PATH=\$HOME/local/llvm-v$ver/tools/clang/tools/scan-build:\$PATH"
