#!/usr/bin/env bash
set -e
abort() {  echo "$@" 1>&2 && exit 1; }

version=$(wget -qO- https://nodejs.org/download/release/index.tab | sed -n 2p | cut -f1)
test -n "$version" || abort missing nodejs.org/download/release/index.tab

echo installing $version
mkdir -p ~/local/node-$version
cd ~/local/node-$version
wget -qO- https://nodejs.org/download/release/$version/node-$version-linux-x64.tar.gz | tar xz --strip-components=1

# Update local/node/bin symlink to use newly downloaded version
mkdir -p ~/local/node
ln -sf ~/local/node-$version/bin ~/local/node/bin

echo "Remember to:"
echo "export PATH=\$HOME/local/node/bin:\$PATH"
