#!/usr/bin/env bash
set -e

globalModules=(
  ansimd      # markdown viewer terminal
  badgify     # badge generator
  faucet      # tap formatter
  tub         # tap formatter
  eslint      # static analysis
  jshint      # static analysis
  jsonlint    # analysis of json files
  json        # curl jsonUrl | json key
  pkginit     # for quick making a npm module shell (though bugged atm)
  browserify  # npm style webapps
  testling    # for browser tests
  asciify     # CLI asciifier
  ytdl        # streaming youtube downloader
  symlink     # node module link helper
  badgify     # readme badge generator
  bower       # web components currently here..
  pm2         # process manager
  polylint    # linter for polymer
  marked-man  # man page generator
  zalgolize   # fun stuff
)

for i in "${globalModules[@]}"; do
  echo "$i"
  npm install -g "$i"
done

pkginit add default ~/.templates/npm/pkg.json
