#!/usr/bin/env bash

# only set prefix if we didn't install from source
npm install -g npm # update npm first

globalModules=(
  ansimd      # markdown viewer terminal
  badgify     # badge generator
  faucet      # tap formatter
  eslint      # static analysis
  jshint      # static analysis
  jsonlint    # analysis of json files
  json        # curl jsonUrl | json key
  nd          # nd `moduleName` for README.md in stdout
  pkginit     # for quick making a npm module shell (though bugged atm)
  browserify  # npm style webapps
  testling    # for browser tests
  kill-tabs   # party trick
  asciify     # CLI asciifier
  ytdl        # streaming youtube downloader
  symlink     # node module link helper
  badgify     # readme badge generator
  bower       # web components currently here..
  pm2         # process manager
  polylint    # linter for polymer
  # tests
  nodeunit
  istanbul
  tap
  coveralls
  jscoverage
  vulcanize   # polymer concat
)

for i in "${globalModules[@]}"
do
  echo $i
  npm install -g $i
done

pkginit add default templates/npm/pkg.json
