#!/usr/bin/env bash
set -e

globalModules=(
  badgify     # badge generator
  faucet      # tap formatter
  eslint      # static analysis
  jshint      # static analysis
  jsonlint    # analysis of json files
  json        # curl jsonUrl | json key
  js-yaml     # yaml key helper
  pkginit     # npm init helper
  browserify  # common js bundler
  asciify     # CLI asciifier
  ytdl        # streaming youtube dl
  symlink     # node module link helper
  badgify     # readme badge generator
  bower       # web components temp
  pm2         # process manager
  polylint    # linter for polymer
  marked-man  # man page generator
  yr-cli      # weather forecasts
  zalgolize   # fun stuff
)

for i in "${globalModules[@]}"; do
  echo "$i"
  npm install -g "$i"
done

pkginit add default ~/.templates/npm/pkg.json
