#!/bin/bash

pacs=(
  bash-completion
  ccze
  cmake
  cowsay
  git
  gimp
  gnome-terminal
  htop
  imagemagic
  lolcat
  lsb-release
  mpd
  mumble
  ncmpcpp
  ntfs-3g
  nmap
  openssh
  profanity
  redshift
  rsync
  pass
  vlc
  wget
  xclip
  xorg-xrandr
)

for p in "${pacs[@]}"; do
  pacman -S "$p"
done

# haskell
pacman -S ghc cabal-install shellcheck

# llvm
pacman -S clang clang-analyzer clang-tools-extra lldb

# python
pacman -S python-pip

# ssh stuff
pacman -S keychain x11-ssh-askpass

# misc others
pacman -S nemo-fileroller ttf-ubuntu-font-family

# steam
pacman -S steam lib32-alsa-plugins lib32-nvidia-libgl
