#!/bin/bash
set -e

# CLIs
pacman -S ccze git lolcat lsb-release nmap rsync

# terminals
pacman -S bash-completion cowsay rxvt-unicode tmux xterm

# TUIs
pacman -S htop profanity weechat

# haskell
pacman -S ghc cabal-install shellcheck

# c++
pacman -S cmake clang clang-analyzer clang-tools-extra lldb

# python
pacman -S python-pip

# rust
pacman -S rust cargo

# ssh + key/pass managers
pacman -S keychain x11-ssh-askpass pass openssh

# music
pacman -S mpc mpd ncmpcpp

# video (force libx264 over libx264-10bit for now)
pacman -S libx264 openshot vlc

# network
pacman -S vpnc

# X related
pacman -S gnome-screenshot mumble redshift xclip xdotool xorg-xrandr xorg-xrdb

# media
pacman -S feh gimp gthumb imagemagick

# filesystems
pacman -S ntfs-3g nemo-fileroller nemo-share samba

# steam
pacman -S steam lib32-alsa-plugins lib32-nvidia-libgl

# dev services
pacman -S docker postgresql

# misc
pacman -S firefox ttf-ubuntu-font-family
