#!/usr/bin/env bash
set -e

pip install -U pip

globalModules=(
  ghp-import
  mercurial_keyring
  pyflakes
  pylint
  shyaml
)

for i in "${globalModules[@]}"; do
  echo "$i"
  pip install --user "$i"
done
