#!/bin/bash
set -e

PROFANITY_VER="0.4.7"
STROPHE_VER="0.8.8"

mkdir -p xmpp && cd xmpp

wget -qO- https://github.com/boothj5/profanity/archive/${PROFANITY_VER}.tar.gz | tar xz
wget -qO- https://github.com/strophe/libstrophe/archive/${STROPHE_VER}.tar.gz | tar xz

cd libstrophe-${STROPHE_VER}
mkdir -p m4
./bootstrap.sh
./configure --prefix=/usr
make -j8
make install
cd ..

cd profanity-${PROFANITY_VER}
mkdir -p m4
./bootstrap.sh
./configure --enable-otr
make -j8
make install

cd ../..
rm -rf xmpp
