#!/usr/bin/env bash

cd && cd repos

# private bitbucket repos
privates=(
  deathmatch
  ssh
  meshrtc
)
for i in ${privates[@]}
do
  echo $i
  git clone git@bitbucket.org:clux/$i.git
done

echo "Retrieving ssh config"
git clone git@bitbucket.org:clux/ssh.git ~/.ssh

# tournament related modules
cd && cd repos
mkdir tournament && cd tournament
trn=(
  duel
  #duel-names
  ffa
  ffa-tb
  group
  groupstage
  groupstage-tb
  groupstage-tb-duel
  masters
  roundrobin
  tiebreaker
  tournament
  tournament-components
  tourney
)
for i in ${trn[@]}
do
  echo $i
  git clone git@github.com:clux/$i.git
done

misc=(
  autonomy
  #badgify
  bandage
  blog
  cleverbot-irc
  combustion
  confortable
  curvefever-bot
  curvefever-stats
  decay
  deus-login
  dotclux
  dye
  gu
  icebreaker
  interlude
  irc-stream
  linkr-app
  linkr-components
  #logule
  mddocs
  npm-graph
  operators
  posts
  preservative
  sdp-transform
  smell
  splitter
  subset
  sulfur
  #symlink
  tabexplode
  tf2configs
  topiary
  trials
  tub
  unitednationsoftheworld
  vitae
  wolfram-alpha
  wolfram-irc
  wrappers
  xmpp-stream
  zalgolize
)

cd && cd repos

for i in ${misc[@]}
do
  echo $i
  git clone git@github.com:clux/$i.git
done

cd
symlink repos repos/tournament -g nodeunit -g jscoverage -g coveralls -g istanbul --execute
