#!/bin/bash
set -e

cd ~/repos

# Personal stuff
git hub-clux dotclux tf2configs vitae
git bucket-clux dotcisco gpg-pass mumble-keys ssh

./ssh/install.sh
./gpg-pass/install.sh
./mumble-keys/install.sh
