#!/bin/sh

# generate ssh keys
ssh-keygen -t rsa -C "analsandblaster@gmail.com" -f ~/.ssh/github_id_rsa
xclip -sel clip < ~/.ssh/github_id_rsa.pub
echo "LOG IN TO DVCS AND PASTE RSA KEY (IN CLIPBOARD NOW)"
echo "VERIFY GITHUB WITH: ssh -T git@github.com"
