#!/bin/sh
url=$(wget -q http://www.sublimetext.com/3 -O - | \
    tr "\t\r\n'" '   "' | \
    grep -i -o '<a[^>]\+href[ ]*=[ \t]*"\(ht\|f\)tps\?:[^"]\+"' | \
    sed -e 's/^.*"\([^"]\+\)".*$/\1/g' | \
    grep "amd64.deb")

echo $url
wget $url

file=$(echo $url | sed 's/.*.com\///')
sudo dpkg -i $file
