---
# sshd

- template:
    src: templates/motd.sh
    dest: '/etc/profile.d/motd.sh'
    mode: 0644

- template:
    src: templates/sshd_config.j2
    dest: '/etc/ssh/sshd_config'
    mode: 0644
  notify:
  - restart sshd

- service:
    name: sshd
    state: started
    enabled: true
