---
# brew interface

# NB: currently does not work, inlined in firstboot.sh
# - name: Install casks
#   community.general.homebrew:
#     name: "{{ item }}"
#     upgrade_options: "--cask"
#     state: present
#   with_items:
#   - docker
#   - firefox
#   - google-chrome
#   - iterm2
#   - alacritty
#   - slack
#   - visual-studio-code
#   - tuple

- name: Install formulas
  community.general.homebrew:
    formula: "{{ item }}"
    state: present
  with_items:
  # gnu tools are massively outdated or missing on mac
  - bash
  - bash-completion@2
  - binutils
  - coreutils
  - diffutils
  - findutils
  - gnu-sed
  - gnu-tar
  - gpatch
  - gnupg
  - grep
  - less
  - make
  - rsync
  - watch
  - ssh-copy-id
  # cli
  - jq
  - fzf
  - pass
  - hyperfine
  - exa
  - just
  - tokei
  - protobuf
  - bat
  - bats-core
  - fd
  - sd
  - ripgrep
  - shellcheck
  - starship
  - vivid
  - helix
  - rust-analyzer
  - genact
  - pwgen
  - procs
  - direnv
  - dust
  - ruff
  - zoxide
  - choose-rust
  - git-delta
  - fastmod
  - ncspot
  - keychain
  - zola
  - zinit
    #- zsh-fast-syntax-highlighting
    #- zsh-autosuggestions
  # python modules (because mac is bad at python)
  - youtube-dl
  - yamllint
  - pyyaml
  - python-yq
  # cloud
  - kubectl
  - k3d
  - helm
  - kdash-rs/kdash/kdash
  - k9s
  - homeport/tap/dyff
  - fluxcd/tap/flux
  - int128/kubelogin/kubelogin
  - terraform
  # fonts
  - font-inconsolata-nerd-font
