---
# brew interface

# NB: currently does not work, inlined in firstboot.sh
# - name: Install casks
#   community.general.homebrew:
#     name: "{{ item }}"
#     upgrade_options: "--cask"
#     state: present
#   with_items:
#   - docker
#   - firefox
#   - google-chrome
#   - iterm2
#   - alacritty
#   - slack
#   - visual-studio-code
#   - tuple

- name: Install formulas
  community.general.homebrew:
    formula: "{{ item }}"
    state: present
  with_items:
  # gnu tools are massively outdated or missing on mac
  - bash
  - bash-completion@2
  - binutils
  - coreutils
  - diffutils
  - findutils
  - gnu-sed
  - gnu-tar
  - gpatch
  - gnupg
  - grep
  - less
  - make
  - rsync
  - vim
  - watch
  - ssh-copy-id
  # cli
  - jq
  - fzf
  - pass
  - hyperfine
  - exa
  - tree
  - terraform
  - tokei
  - bat
  - fd
  - ripgrep
  - starship
  - procs
  - zoxide
  - choose-rust
  - fastmod
  # python modules (because mac is bad at python)
  - youtube-dl
  - yamllint
  - pyyaml
  - python-yq
  # cloud
  - kubectl
  - k3d
