---

# Misc linux tweaks

# https://www.phoronix.com/news/Fedora-39-VM-Max-Map-Count
- name: sysctl vm.max_map_count
  become: true
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: '2147483642'
    sysctl_set: true

- name: symlink hx -> helix
  become: true
  file:
    src: /sbin/helix
    dest: /usr/local/bin/hx
    owner: clux
    group: clux
    state: link

- name: net capabilities on nethogs
  community.general.capabilities:
    path: '/sbin/nethogs'
    capability: '{{ item }}'
  with_items:
  - "cap_net_admin+ep"
  - "cap_net_raw+ep"
- name: net capabilities on bandwhich
  community.general.capabilities:
    path: /sbin/bandwhich
    capability: cap_net_raw,cap_net_admin+ep

- name: pulseaudio disable source/sink idle suspend
  become: true
  lineinfile:
    path: /etc/pulse/default.pa
    regexp: 'load-module module-suspend-on-idle'
    line: '###load-module module-suspend-on-idle'
