---
# Core Arch Linux Setup

- import_tasks: pacman.yml
  when: ansible_os_family == "Archlinux"
  become: yes
  tags: [arch, core]

- import_tasks: services.yml
  when: ansible_os_family == "Archlinux"
  become: yes
  tags: [arch, core]

- import_tasks: systemd.yml
  when: ansible_os_family == "Archlinux"
  become: yes
  tags: [arch, core]

# https://www.phoronix.com/news/Fedora-39-VM-Max-Map-Count
- name: sysctl vm.max_map_count
  tags: [arch, core]
  become: yes
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: '2147483642'
    sysctl_set: true

- name: Link hx -> helix
  tags: [arch, core]
  become: yes
  ansible.builtin.file:
    src: /sbin/helix
    dest: /usr/local/bin/hx
    owner: clux
    group: clux
    state: link
