---
# systemd

# Services that can run as --user (that haven't auto-started)
- name: systemctl enable user services
  systemd:
    name: '{{ item }}'
    state: started
    enabled: true
    scope: 'user'
  become: false
  with_items: []
  #- mpd

#- name: Enable pcscd service for yubikey
#  systemd:
#    name: pcscd
#    enabled: true
#    state: started
#- name: Enable systemd-resolved for openvpn
#  systemd:
#    name: systemd-resolved
#    enabled: true
#    state: started
