---
# systemd

# Services that can run as --user (that haven't auto-started)
- name: systemctl enable user services
  systemd: name={{ item }} state=started enabled=yes user=yes
  become: no
  with_items: []
  #- mpd

#- name: Enable pcscd service for yubikey
#  systemd:
#    name: pcscd
#    enabled: yes
#    state: started
#- name: Enable systemd-resolved for openvpn
#  systemd:
#    name: systemd-resolved
#    enabled: yes
#    state: started

# getty (autologin)
- name: getty config dir
  file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory

# Tweak a few lines in config - shows up in systemctl show docker
- name: getty autologin
  template:
    src: "templates/gettyautologin.conf"
    dest: "/etc/systemd/system/getty@tty1.service.d/autologin.conf"
