---
# install rust components via rustup and cargo

# fetch stable toolchain
- name: rustup update stable
  command: rustup update stable
  register: stable_output
  changed_when:
  - "'downloading' in stable_output.stderr"

# make sure it's set up properly before we use it
- name: rustup default stable
  command: rustup default stable
  register: rustup_result
  changed_when: "'unchanged' not in rustup_result.stdout"

# because we most frequently need to recompile nightly modules, do nightly stuff first
- name: rustup update nightly
  command: rustup update nightly
  when: recompile_tasks | default(false)
  register: nightly_output
  changed_when:
  - "'downloading' in nightly_output.stderr"

- name: install modules on rustup nightly
  command: rustup run nightly cargo install {{ item }} --force
  with_items: []
  when:
  - (recompile_tasks | default(false)) or nightly_output.changed


# large batch of stable modules (if needed)
# NB: many of these are already installed via pacman:
# sd,zoxide,ripgrep,exa,hyperfine,fd,bat,tokei,procs
- name: install modules on rustup stable
  command: cargo install {{ item }} --force
  when:
  - (recompile_tasks | default(false)) or stable_output.changed
  with_items:
  - racer
  - cargo-edit
  - cargo-tree
  - cargo-outdated
  #- cargo-tarpaulin (nightly)
  - cargo-audit
  - cargo-expand
  - choose
  - du-dust
  - ytop
  - grex
  - hors
  - xsv
