---
# install rust components via rustup and cargo

# fetch stable toolchain
- name: rustup update stable
  command: rustup update stable
  register: stable_rust_output
  changed_when:
  - "'downloading' in stable_rust_output.stderr"

- name: install cargo modules
  community.general.cargo:
    name: '{{ item }}'
    state: "{{ pkg_state }}"
  with_items:
  - cargo-tarpaulin # not in brew (bad mac support?)
  - cargo-expand # not in brew
  - toml2json
  - fastmod # not in pacman, but in brew
