---
# install rust components via rustup and cargo

# fetch stable toolchain
- name: rustup update stable
  command: rustup update stable
  register: stable_output
  changed_when:
  - "'downloading' in stable_output.stderr"

- set_fact:
    cargo_state: "{{ 'latest' if (upgrade_tasks | default(false)) else 'present' }}"

- name: install cargo modules
  community.general.cargo:
    name: '{{ item }}'
    state: '{{ cargo_state }}'
  with_items:
  - cargo-edit
  - cargo-tree
  - cargo-outdated
  - cargo-tarpaulin
  - cargo-release
  - cargo-audit
  - cargo-expand
  - ytop
  - toml2json
  - fastmod
