---
# npm playbook - install cli tools globally

# We generally do not develop js anymore so this is currently empty
# For CLIs, prefer stable versions from pacman/brew.

- name: npm config set prefix ~/.node_modules
  lineinfile:
    dest: /home/{{ user }}/.npmrc
    regexp: '^prefix='
    line: 'prefix=/home/{{ user }}/.node_modules'

- name: Install global npm dependencies
  community.general.npm:
    name: '{{ item }}'
    state: "{{ pkg_state }}"
    global: true
  with_items: []
  #- faucet
  #- eslint
  #- jshint
  #- asciify
  #- marked-man
  #- reveal-md
  #- zalgolize
