---
# pip playbook - install cli tools in pip user dir

# NB: pip is managed by pacman

- set_fact:
    pip_state: "{{ 'latest' if (upgrade_tasks | default(false)) else 'present' }}"

# Some of these technically do exist as well in pacman, but want some updates faster
- name: Install dependencies
  pip: name={{ item }} extra_args='--user' state={{pip_state}}
  with_items:
  #- ghp-import
  #- pyaml
  - yq
  - requests
  - yamllint
  - yt-dlp
  #- pipenv
  #- pytest
  #- magic-wormhole
